name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: cd ui; npm install
    - name: build
      run: cd ui; npm run build
    - name: deploy
      run: npm run deploy
